export const FETCH_MOVIES_SINGLE_REQUEST = 'FETCH_MOVIES_SINGLE_REQUEST';
export const FETCH_MOVIES_SINGLE_SUCCESS = 'FETCH_MOVIES_SINGLE_SUCCESS';
export const FETCH_MOVIES_SINGLE_FAILURE = 'FETCH_MOVIES_SINGLE_FAILURE';
